config/routes.rb
Rails.application.routes.draw do
  resources :cocktails do 
    resources :doses, only: [:new, :create]   
  end
  resources :doses, only: [:destroy]
end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :ingredients, through: :doses
  has_many :doses, dependent: :destroy

  validates :name, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader

end

app/models/dose.rb
class Dose < ActiveRecord::Base
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail_id, :ingredient_id, presence: true
  validates :ingredient_id, uniqueness: { scope: :cocktail_id}
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index 
    @cocktails = Cocktail.all
    @ingredients = Ingredient.all
  end

  def show 
    @cocktail = Cocktail.find(params[:id])
  end

  def new 
    @cocktail = Cocktail.new
    @ingredients = Ingredient.all
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else 
      render 'new'
    end
  end

  def edit 
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :dose,:photo, :photo_cache)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
    @ingredients = Ingredient.all - @cocktail.ingredients
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])

    @dose = @cocktail.doses.build(dose_params)

    if @dose.save
      redirect_to cocktail_path(@dose.cocktail_id)
    else 
      render 'new'
    end
  end

    def destroy
      @dose = Dose.find(params[:id])
      @cocktail = @dose.cocktail
      @dose.destroy!
      redirect_to cocktail_path(@cocktail)
    end


  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<h1>Edit the <%= @cocktail.name %></h1>

<%= render 'layouts/form' %>

app/views/cocktails/index.html.erb
<div class="container" style="text-align: center">
<h1>Mister cocktail app</h1>

<%= cl_image_tag("bkrzu4gvbacya2lpxd2m.jpg",
      width: 400, height: 300, crop: :fill) %>
<hr>
<table class="table">
<% @cocktails.each do |cocktail| %>
  <tr>
    <td><%=  cocktail.name %>    </td>
    <%# end %>
    <td>
  <%= link_to 'Show', cocktail_path(cocktail), class:"btn btn-danger" %>  
<%= link_to 'Edit', edit_cocktail_path(cocktail), class:"btn btn-danger" %>
<%= link_to 'Delete', cocktail_path(cocktail), method: :delete, class:"btn btn-danger" %></td>
    <% end %>
  </tr>
</table>

<hr>

  <%= link_to "New cocktail", new_cocktail_path, class:"btn btn-danger" %>

</div>


<ul>
  <li>
    
  </li>
</ul>

app/views/cocktails/new.html.erb
<h1>Add a new cocktail!</h1>

<%= render 'layouts/form' %>

app/views/cocktails/show.html.erb
<div class="banner">

  <div class="container">
  <div class="row">
    <div class="col-xs-12">
      

    <%= cl_image_tag @cocktail.photo, height: 300, width: 400 %>
    <h2><%= @cocktail.name %></h2>
    <table>
      <tr>
        <th>Dose</th>
        <th>Ingredient</th>
        <th>Delete</th>
      </tr>
      <tr>
        <% @cocktail.doses.each do |dose| %>
        <td> <%= dose.description %></td>
        <td><%= dose.ingredient.name %></td>
        <td><%= link_to "Delete", dose_path(dose), method: :delete, class:"btn btn-danger"%></td>
      </tr>
    </table>

    <% end %>

  </table>

  <hr>

  <%= link_to 'Add ingredients', new_cocktail_dose_path(@cocktail), class:"btn btn-danger" %>
  <%= link_to 'All cocktails', cocktails_path, class:"btn btn-danger" %>

    </div>
  </div>
</div>
</div>

app/views/doses/new.html.erb
<h1>ingredients + doses for <%= @cocktail.name %></h1>

<%= link_to 'Back to cocktails', cocktail_path(@cocktail) %>


<%= simple_form_for [:cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.input :ingredient_id, collection: @ingredients %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name, prompt: "name" %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "add a cocktail" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MisterCocktail</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>